### ISSUE TITLE
Getting fileapi.h missing error.

### ISSUE THREAD

**Issue by Bigbossbro08** [withmorten/rge_campaign#1]
When I'm trying compile the source, I am getting fileapi.h is missing error. Is there specific version of Mingw that needs to be run? I'm using MingW 6.3.0 by the way.

**Comment by withmorten** [comment]
Mh, I'm using MSYS2 ... a kind of "unix " style installation, it works fine there.

https://www.msys2.org

You can use it in standard mingw fashion as well, but it's a lot better with packages etc

**Comment by withmorten** [comment]
As a note, I'm only including that for GetFileTime and SetFileTime (I think it's nice when the scn/scx files have the same date as the campaigns they're from), you can probably not include that and remove all the stuff throwing errors afterwards :P

But I can only suggest grabbing msys2 instead of the mingw installations.

By creating this batch file in the msys2 install folder, you can use it as you would mingw for certain build processes, but have the advantage of installing packages like zlib, iconv etc via pacman:

    @echo off
    set PATH=C:\msys\mingw32\bin;C:\Windows;C:\Windows\system32;C:\Program Files\CMake\bin
    cd "C:\"
    "C:\Windows\system32\cmd.exe"

**Comment by withmorten** [comment]
I'm going to close this, reopen if you have another issue compiling it!
