### ISSUE TITLE
CPN vs CPX

### ISSUE THREAD

**Issue by sandsmark** [withmorten/rge_campaign#2]
I implemented support for reading CPN and CPX files some time ago in genieutils (for freeaoe), but when I tested with cpn files I couldn't get a clean decompression of the scn files (and seemed to have more data in the header):
https://github.com/sandsmark/genieutils/blob/master/include/genie/script/ScnFile.h#L146-L147

Have you seen this, or is there something else I fucked up in my implementation?

**Comment by withmorten** [comment]
Hey man, I totally forgot about this after clicking way the mail a while ago. Sorry for not getting back sooner. Just out of curiosity, are you on the SE discord and who are you there?

As far as I can tell CPN from AoK and CPX from AoC are the exact same format, just using different extensions to distinguish what scenarios they include. That leaked AoK HD alpha build does not distinguish struct wise between these formats at all, and AoE1 even has the exact same struct. So the format should be exactly the same for CPN and CPX.

The structs I used in the headers for my little tool are the original structs - in your header I see you using std::string, while they are actually fixed length char arrays regardless of actual scenario name length - which you can see by the bunch of zeros in the cpn/cpx files in a hexeditor. Any string in these formats should be `char xxx[255]`.

I unfortunately don't know *anything* about the SCN/SCX file format - so I don't know why that breaks, except that you maybe start reading at the wrong offset.

I tested the extracted scenarios and they open fine in anything that opens scenarios, and the game accepts the repacked campaigns (and they are byte exact the same file when I repack the scenarios, except for some extra strings which get ignored because they're hidden after a 0 terminator after the campaign name).

**Comment by sandsmark** [comment]
Thanks for getting back to me (and no problem about the delay). And CPX files work fine for now, so CPN support hasn't really been important enough to look into the format.

Ref. the strings; genieutils uses std::strings everywhere, but the deserializers put stuff in them in the appropriate way depending on the file format, so for those fixed length strings it has an overload that takes the number of bytes: https://github.com/sandsmark/genieutils/blob/master/src/script/ScnFile.cpp#L408

I was dumb enough to reverse the CPX format by hand with a hex editor (instead of looking for/at other implementations), so I'm aware about the fixed size identifiers. :-)

I'm not a huge fan of the template-heavy serialization approach used in genieutils, but I didn't want to implement everything from scratch, so it was easier to start with freeaoe and genieutils and work from there. But it's fairly efficient and the code gets pretty clean, so I've just kept using the same pattern for now.

And I'm not on discord, aoe stuff is just something I do a couple of hours every other week or so.

**Comment by withmorten** [comment]
Ah, right.

Perhaps this is wrong?

serialize(filename, 257);

Should be 255 as well?

Yeah I can see why one would not be a huge fan of it in any case.

About discord, I was just wondering because I only posted this on an AoE2 modding related discord server and nowhere else, and was wondering how you discovered it :D

**Comment by sandsmark** [comment]
I was just looking around for cpn/cpx documentation. :-)

**Comment by withmorten** [comment]
Interesting how quick google is with updating that kind of stuff. :D

Btw, a while ago I compiled your versions of AGE, genieutils etc (they don't have issue trackers I think so I'm just mentioning it here) - and they work fine, except for when opening HD data - the units open fine at first, but as soon as you search or select a unit, the whole program freezes and infinite loops at 25% CPU. I didn't want to debug the issue so I just compiled an older version of tapsas and implemented some changes I wanted myself from goto-bus-stop, but maybe you have an idea why that is :)
